### ISSUE TITLE
Класс для отправки ответов в тред.

### ISSUE THREAD

**Issue by AndreiDrang** [anonim-legivon/dvach.api#1]
Сделать класс для отправки ответов на конкретный пост в тред, а так же отправки обычных постов в тред.

**Comment by fadedDexofan** [comment]
@AndreiDrang Первая пошла

**Comment by AndreiDrang** [comment]
+ доделать отправку файлов.

**Comment by AndreiDrang** [comment]
**TODO :** Обнуление капчи.

**Comment by fadedDexofan** [comment]
https://github.com/anonim-legivon/dvach.api/blob/9658bcb0995db9665fc63b7fd5c7ddc13073181c/api2ch/api.py
