### ISSUE TITLE
Сделать обработчки капчи.

### ISSUE THREAD

**Issue by AndreiDrang** [anonim-legivon/dvach.api#2]
Сделать новый обработчик капчи на основе двух сервисов, на выбор: AntiCaptcha и RuCaptcha.
Возможно ещё какой-то сервис прикрутить - по желанию.

**Comment by fadedDexofan** [comment]
https://github.com/anonim-legivon/dvach.api/commit/c85e02b036349b84e8ab444819d4c9cbf111aa92
https://github.com/anonim-legivon/dvach.api/commit/876003cb4bcd69d7346e97b4136de3cd30656614

**Comment by AndreiDrang** [comment]
С получением капчи и её проверкой - всё. Для решения капчи нужны отдельные библиотеки и сервисы.
