### ISSUE TITLE
Сделать класс Settings

### ISSUE THREAD

**Issue by slowpojkee** [anonim-legivon/dvach.api#4]
https://2ch.hk/makaba/mobile.fcgi?task=get_boards
- Сделать класс Settings.
- Загрузку настроек всех борд сразу в list []
- Вызов через api.board.settings

**Comment by fadedDexofan** [comment]
https://github.com/anonim-legivon/dvach.api/commit/451b0e2c4fa6aacb869b99ce8f33d837f50def68

**Comment by fadedDexofan** [comment]
451b0e2c4fa6aacb869b99ce8f33d837f50def68

**Comment by slowpojkee** [comment]
`class Settings` -> `class Board`
Загрузка настроек всех борд в `Api._boards` происходит при создании объекта класса `Api`,
доступ к настройкам борды через атрибуты `self.board`
Так же, можно менять борду не пересоздавая `Api`, объект `Board `подставиться автоматически
Например:
```
api = api2ch.Api('b')
print(api.board.name)
api.board = 'vg'
print(api.board.name)
```
